<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \DB::table('languages')->delete();

        \DB::table('languages')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'rtl' => 0,
                    'name' => 'Afrikaans',
                    'short' => 'af',
                    'image_dir' => NULL,
                    'image' => 'af.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            1 =>
                array (
                    'id' => 2,
                    'rtl' => 0,
                    'name' => 'Albanian - shqip',
                    'short' => 'sq',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            2 =>
                array (
                    'id' => 3,
                    'rtl' => 0,
                    'name' => 'Amharic - አማርኛ',
                    'short' => 'am',
                    'image_dir' => NULL,
                    'image' => 'am.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            3 =>
                array (
                    'id' => 4,
                    'rtl' => 1,
                    'name' => 'Arabic - العربية',
                    'short' => 'ar',
                    'image_dir' => NULL,
                    'image' => 'ar.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            4 =>
                array (
                    'id' => 5,
                    'rtl' => 0,
                    'name' => 'Aragonese - aragonés',
                    'short' => 'an',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            5 =>
                array (
                    'id' => 6,
                    'rtl' => 0,
                    'name' => 'Armenian - հայերեն',
                    'short' => 'hy',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            6 =>
                array (
                    'id' => 7,
                    'rtl' => 0,
                    'name' => 'Asturian - asturianu',
                    'short' => 'ast',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            7 =>
                array (
                    'id' => 8,
                    'rtl' => 0,
                    'name' => 'Azerbaijani - azərbaycan dili',
                    'short' => 'az',
                    'image_dir' => NULL,
                    'image' => 'az.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            8 =>
                array (
                    'id' => 9,
                    'rtl' => 0,
                    'name' => 'Basque - euskara',
                    'short' => 'eu',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            9 =>
                array (
                    'id' => 10,
                    'rtl' => 0,
                    'name' => 'Belarusian - беларуская',
                    'short' => 'be',
                    'image_dir' => NULL,
                    'image' => 'be.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            10 =>
                array (
                    'id' => 11,
                    'rtl' => 0,
                    'name' => 'Bengali - বাংলা',
                    'short' => 'bn',
                    'image_dir' => NULL,
                    'image' => 'bn.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            11 =>
                array (
                    'id' => 12,
                    'rtl' => 0,
                    'name' => 'Bosnian - bosanski',
                    'short' => 'bs',
                    'image_dir' => NULL,
                    'image' => 'bs.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            12 =>
                array (
                    'id' => 13,
                    'rtl' => 0,
                    'name' => 'Breton - brezhoneg',
                    'short' => 'br',
                    'image_dir' => NULL,
                    'image' => 'br.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            13 =>
                array (
                    'id' => 14,
                    'rtl' => 0,
                    'name' => 'Bulgarian - български',
                    'short' => 'bg',
                    'image_dir' => NULL,
                    'image' => 'bg.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            14 =>
                array (
                    'id' => 15,
                    'rtl' => 0,
                    'name' => 'Catalan - català',
                    'short' => 'ca',
                    'image_dir' => NULL,
                    'image' => 'ca.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            15 =>
                array (
                    'id' => 16,
                    'rtl' => 0,
                    'name' => 'Central Kurdish - کوردی (دەستنوسی عەرەبی)',
                    'short' => 'ckb',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            16 =>
                array (
                    'id' => 17,
                    'rtl' => 0,
                    'name' => 'Chinese - 中文',
                    'short' => 'zh',
                    'image_dir' => NULL,
                    'image' => 'cn.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            17 =>
                array (
                    'id' => 18,
                    'rtl' => 0,
                    'name' => 'Chinese (Hong Kong) - 中文（香港）',
                    'short' => 'zh-HK',
                    'image_dir' => NULL,
                    'image' => 'cn.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            18 =>
                array (
                    'id' => 19,
                    'rtl' => 0,
                    'name' => 'Chinese (Simplified) - 中文（简体）',
                    'short' => 'zh-CN',
                    'image_dir' => NULL,
                    'image' => 'cn.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            19 =>
                array (
                    'id' => 20,
                    'rtl' => 0,
                    'name' => 'Chinese (Traditional) - 中文（繁體）',
                    'short' => 'zh-TW',
                    'image_dir' => NULL,
                    'image' => 'cn.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            20 =>
                array (
                    'id' => 21,
                    'rtl' => 0,
                    'name' => 'Corsican',
                    'short' => 'co',
                    'image_dir' => NULL,
                    'image' => 'co.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            21 =>
                array (
                    'id' => 22,
                    'rtl' => 0,
                    'name' => 'Croatian - hrvatski',
                    'short' => 'hr',
                    'image_dir' => NULL,
                    'image' => 'hr.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            22 =>
                array (
                    'id' => 23,
                    'rtl' => 0,
                    'name' => 'Czech - čeština',
                    'short' => 'cs',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            23 =>
                array (
                    'id' => 24,
                    'rtl' => 0,
                    'name' => 'Danish - dansk',
                    'short' => 'da',
                    'image_dir' => NULL,
                    'image' => 'de.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            24 =>
                array (
                    'id' => 25,
                    'rtl' => 0,
                    'name' => 'Dutch - Nederlands',
                    'short' => 'nl',
                    'image_dir' => NULL,
                    'image' => 'nl.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            25 =>
                array (
                    'id' => 26,
                    'rtl' => 0,
                    'name' => 'English',
                    'short' => 'en',
                    'image_dir' => NULL,
                    'image' => 'us.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            26 =>
                array (
                    'id' => 27,
                    'rtl' => 0,
                    'name' => 'English (Australia)',
                    'short' => 'en-AU',
                    'image_dir' => NULL,
                    'image' => 'au.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            27 =>
                array (
                    'id' => 28,
                    'rtl' => 0,
                    'name' => 'English (Canada)',
                    'short' => 'en-CA',
                    'image_dir' => NULL,
                    'image' => 'ca.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            28 =>
                array (
                    'id' => 29,
                    'rtl' => 0,
                    'name' => 'English (India)',
                    'short' => 'en-IN',
                    'image_dir' => NULL,
                    'image' => 'in.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            29 =>
                array (
                    'id' => 30,
                    'rtl' => 0,
                    'name' => 'English (New Zealand)',
                    'short' => 'en-NZ',
                    'image_dir' => NULL,
                    'image' => 'nz.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            30 =>
                array (
                    'id' => 31,
                    'rtl' => 0,
                    'name' => 'English (South Africa)',
                    'short' => 'en-ZA',
                    'image_dir' => NULL,
                    'image' => 'za.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            31 =>
                array (
                    'id' => 32,
                    'rtl' => 0,
                    'name' => 'English (United Kingdom)',
                    'short' => 'en-GB',
                    'image_dir' => NULL,
                    'image' => 'gb.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            32 =>
                array (
                    'id' => 33,
                    'rtl' => 0,
                    'name' => 'English (United States)',
                    'short' => 'en-US',
                    'image_dir' => NULL,
                    'image' => 'us.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            33 =>
                array (
                    'id' => 34,
                    'rtl' => 0,
                    'name' => 'Esperanto - esperanto',
                    'short' => 'eo',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            34 =>
                array (
                    'id' => 35,
                    'rtl' => 0,
                    'name' => 'Estonian - eesti',
                    'short' => 'et',
                    'image_dir' => NULL,
                    'image' => 'et.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            35 =>
                array (
                    'id' => 36,
                    'rtl' => 0,
                    'name' => 'Faroese - føroyskt',
                    'short' => 'fo',
                    'image_dir' => NULL,
                    'image' => 'fo.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            36 =>
                array (
                    'id' => 37,
                    'rtl' => 0,
                    'name' => 'Filipino',
                    'short' => 'fil',
                    'image_dir' => NULL,
                    'image' => 'ph.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            37 =>
                array (
                    'id' => 38,
                    'rtl' => 0,
                    'name' => 'Finnish - suomi',
                    'short' => 'fi',
                    'image_dir' => NULL,
                    'image' => 'fi.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            38 =>
                array (
                    'id' => 39,
                    'rtl' => 0,
                    'name' => 'French - français',
                    'short' => 'fr',
                    'image_dir' => NULL,
                    'image' => 'fr.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            39 =>
                array (
                    'id' => 40,
                    'rtl' => 0,
                    'name' => 'French (Canada) - français (Canada)',
                    'short' => 'fr-CA',
                    'image_dir' => NULL,
                    'image' => 'fr.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            40 =>
                array (
                    'id' => 41,
                    'rtl' => 0,
                    'name' => 'French (France) - français (France)',
                    'short' => 'fr-FR',
                    'image_dir' => NULL,
                    'image' => 'fr.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            41 =>
                array (
                    'id' => 42,
                    'rtl' => 0,
                    'name' => 'French (Switzerland) - français (Suisse)',
                    'short' => 'fr-CH',
                    'image_dir' => NULL,
                    'image' => 'fr.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            42 =>
                array (
                    'id' => 43,
                    'rtl' => 0,
                    'name' => 'Galician - galego',
                    'short' => 'gl',
                    'image_dir' => NULL,
                    'image' => 'gl.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            43 =>
                array (
                    'id' => 44,
                    'rtl' => 0,
                    'name' => 'Georgian - ქართული',
                    'short' => 'ka',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            44 =>
                array (
                    'id' => 45,
                    'rtl' => 0,
                    'name' => 'German - Deutsch',
                    'short' => 'de',
                    'image_dir' => NULL,
                    'image' => 'de.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            45 =>
                array (
                    'id' => 46,
                    'rtl' => 0,
                    'name' => 'German (Austria) - Deutsch (Österreich)',
                    'short' => 'de-AT',
                    'image_dir' => NULL,
                    'image' => 'de.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            46 =>
                array (
                    'id' => 47,
                    'rtl' => 0,
                    'name' => 'German (Germany) - Deutsch (Deutschland)',
                    'short' => 'de-DE',
                    'image_dir' => NULL,
                    'image' => 'de.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            47 =>
                array (
                    'id' => 48,
                    'rtl' => 0,
                    'name' => 'German (Liechtenstein) - Deutsch (Liechtenstein)',
                    'short' => 'de-LI',
                    'image_dir' => NULL,
                    'image' => 'de.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            48 =>
                array (
                    'id' => 49,
                    'rtl' => 0,
                    'name' => 'German (Switzerland) - Deutsch (Schweiz)',
                    'short' => 'de-CH',
                    'image_dir' => NULL,
                    'image' => 'de.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            49 =>
                array (
                    'id' => 50,
                    'rtl' => 0,
                    'name' => 'Greek - Ελληνικά',
                    'short' => 'el',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            50 =>
                array (
                    'id' => 51,
                    'rtl' => 0,
                    'name' => 'Guarani',
                    'short' => 'gn',
                    'image_dir' => NULL,
                    'image' => 'gn.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            51 =>
                array (
                    'id' => 52,
                    'rtl' => 0,
                    'name' => 'Gujarati - ગુજરાતી',
                    'short' => 'gu',
                    'image_dir' => NULL,
                    'image' => 'gu.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            52 =>
                array (
                    'id' => 53,
                    'rtl' => 0,
                    'name' => 'Hausa',
                    'short' => 'ha',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            53 =>
                array (
                    'id' => 54,
                    'rtl' => 0,
                    'name' => 'Hawaiian - ʻŌlelo Hawaiʻi',
                    'short' => 'haw',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            54 =>
                array (
                    'id' => 55,
                    'rtl' => 0,
                    'name' => 'Hebrew - עברית',
                    'short' => 'he',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            55 =>
                array (
                    'id' => 56,
                    'rtl' => 0,
                    'name' => 'Hindi - हिन्दी',
                    'short' => 'hi',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            56 =>
                array (
                    'id' => 57,
                    'rtl' => 0,
                    'name' => 'Hungarian - magyar',
                    'short' => 'hu',
                    'image_dir' => NULL,
                    'image' => 'hu.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            57 =>
                array (
                    'id' => 58,
                    'rtl' => 0,
                    'name' => 'Icelandic - íslenska',
                    'short' => 'is',
                    'image_dir' => NULL,
                    'image' => 'is.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            58 =>
                array (
                    'id' => 59,
                    'rtl' => 0,
                    'name' => 'Indonesian - Indonesia',
                    'short' => 'id',
                    'image_dir' => NULL,
                    'image' => 'id.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            59 =>
                array (
                    'id' => 60,
                    'rtl' => 0,
                    'name' => 'Interlingua',
                    'short' => 'ia',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            60 =>
                array (
                    'id' => 61,
                    'rtl' => 0,
                    'name' => 'Irish - Gaeilge',
                    'short' => 'ga',
                    'image_dir' => NULL,
                    'image' => 'ga.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            61 =>
                array (
                    'id' => 62,
                    'rtl' => 0,
                    'name' => 'Italian - italiano',
                    'short' => 'it',
                    'image_dir' => NULL,
                    'image' => 'it.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            62 =>
                array (
                    'id' => 63,
                    'rtl' => 0,
                    'name' => 'Italian (Italy) - italiano (Italia)',
                    'short' => 'it-IT',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            63 =>
                array (
                    'id' => 64,
                    'rtl' => 0,
                    'name' => 'Italian (Switzerland) - italiano (Svizzera)',
                    'short' => 'it-CH',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            64 =>
                array (
                    'id' => 65,
                    'rtl' => 0,
                    'name' => 'Japanese - 日本語',
                    'short' => 'ja',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            65 =>
                array (
                    'id' => 66,
                    'rtl' => 0,
                    'name' => 'Kannada - ಕನ್ನಡ',
                    'short' => 'kn',
                    'image_dir' => NULL,
                    'image' => 'kn.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            66 =>
                array (
                    'id' => 67,
                    'rtl' => 0,
                    'name' => 'Kazakh - қазақ тілі',
                    'short' => 'kk',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            67 =>
                array (
                    'id' => 68,
                    'rtl' => 0,
                    'name' => 'Khmer - ខ្មែរ',
                    'short' => 'km',
                    'image_dir' => NULL,
                    'image' => 'km.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            68 =>
                array (
                    'id' => 69,
                    'rtl' => 0,
                    'name' => 'Korean - 한국어',
                    'short' => 'ko',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            69 =>
                array (
                    'id' => 70,
                    'rtl' => 0,
                    'name' => 'Kurdish - Kurdî',
                    'short' => 'ku',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            70 =>
                array (
                    'id' => 71,
                    'rtl' => 0,
                    'name' => 'Kyrgyz - кыргызча',
                    'short' => 'ky',
                    'image_dir' => NULL,
                    'image' => 'ky.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            71 =>
                array (
                    'id' => 72,
                    'rtl' => 0,
                    'name' => 'Lao - ລາວ',
                    'short' => 'lo',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            72 =>
                array (
                    'id' => 73,
                    'rtl' => 0,
                    'name' => 'Latin',
                    'short' => 'la',
                    'image_dir' => NULL,
                    'image' => 'la.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            73 =>
                array (
                    'id' => 74,
                    'rtl' => 0,
                    'name' => 'Latvian - latviešu',
                    'short' => 'lv',
                    'image_dir' => NULL,
                    'image' => 'lv.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            74 =>
                array (
                    'id' => 75,
                    'rtl' => 0,
                    'name' => 'Lingala - lingála',
                    'short' => 'ln',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            75 =>
                array (
                    'id' => 76,
                    'rtl' => 0,
                    'name' => 'Lithuanian - lietuvių',
                    'short' => 'lt',
                    'image_dir' => NULL,
                    'image' => 'lt.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            76 =>
                array (
                    'id' => 77,
                    'rtl' => 0,
                    'name' => 'Macedonian - македонски',
                    'short' => 'mk',
                    'image_dir' => NULL,
                    'image' => 'mk.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            77 =>
                array (
                    'id' => 78,
                    'rtl' => 0,
                    'name' => 'Malay - Bahasa Melayu',
                    'short' => 'ms',
                    'image_dir' => NULL,
                    'image' => 'ms.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            78 =>
                array (
                    'id' => 79,
                    'rtl' => 0,
                    'name' => 'Malayalam - മലയാളം',
                    'short' => 'ml',
                    'image_dir' => NULL,
                    'image' => 'ml.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            79 =>
                array (
                    'id' => 80,
                    'rtl' => 0,
                    'name' => 'Maltese - Malti',
                    'short' => 'mt',
                    'image_dir' => NULL,
                    'image' => 'mt.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            80 =>
                array (
                    'id' => 81,
                    'rtl' => 0,
                    'name' => 'Marathi - मराठी',
                    'short' => 'mr',
                    'image_dir' => NULL,
                    'image' => 'mr.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            81 =>
                array (
                    'id' => 82,
                    'rtl' => 0,
                    'name' => 'Mongolian - монгол',
                    'short' => 'mn',
                    'image_dir' => NULL,
                    'image' => 'mn.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            82 =>
                array (
                    'id' => 83,
                    'rtl' => 0,
                    'name' => 'Nepali - नेपाली',
                    'short' => 'ne',
                    'image_dir' => NULL,
                    'image' => 'ne.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            83 =>
                array (
                    'id' => 84,
                    'rtl' => 0,
                    'name' => 'Norwegian - norsk',
                    'short' => 'no',
                    'image_dir' => NULL,
                    'image' => 'no.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            84 =>
                array (
                    'id' => 85,
                    'rtl' => 0,
                    'name' => 'Norwegian Bokmål - norsk bokmål',
                    'short' => 'nb',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            85 =>
                array (
                    'id' => 86,
                    'rtl' => 0,
                    'name' => 'Norwegian Nynorsk - nynorsk',
                    'short' => 'nn',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            86 =>
                array (
                    'id' => 87,
                    'rtl' => 0,
                    'name' => 'Occitan',
                    'short' => 'oc',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            87 =>
                array (
                    'id' => 88,
                    'rtl' => 0,
                    'name' => 'Oriya - ଓଡ଼ିଆ',
                    'short' => 'or',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            88 =>
                array (
                    'id' => 89,
                    'rtl' => 0,
                    'name' => 'Oromo - Oromoo',
                    'short' => 'om',
                    'image_dir' => NULL,
                    'image' => 'om.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            89 =>
                array (
                    'id' => 90,
                    'rtl' => 0,
                    'name' => 'Pashto - پښتو',
                    'short' => 'ps',
                    'image_dir' => NULL,
                    'image' => 'ps.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            90 =>
                array (
                    'id' => 91,
                    'rtl' => 0,
                    'name' => 'Persian - فارسی',
                    'short' => 'fa',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            91 =>
                array (
                    'id' => 92,
                    'rtl' => 0,
                    'name' => 'Polish - polski',
                    'short' => 'pl',
                    'image_dir' => NULL,
                    'image' => 'pl.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            92 =>
                array (
                    'id' => 93,
                    'rtl' => 0,
                    'name' => 'Portuguese - português',
                    'short' => 'pt',
                    'image_dir' => NULL,
                    'image' => 'pt.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            93 =>
                array (
                    'id' => 94,
                    'rtl' => 0,
                    'name' => 'Portuguese (Brazil) - português (Brasil)',
                    'short' => 'pt-BR',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            94 =>
                array (
                    'id' => 95,
                    'rtl' => 0,
                    'name' => 'Portuguese (Portugal) - português (Portugal)',
                    'short' => 'pt-PT',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            95 =>
                array (
                    'id' => 96,
                    'rtl' => 0,
                    'name' => 'Punjabi - ਪੰਜਾਬੀ',
                    'short' => 'pa',
                    'image_dir' => NULL,
                    'image' => 'pa.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            96 =>
                array (
                    'id' => 97,
                    'rtl' => 0,
                    'name' => 'Quechua',
                    'short' => 'qu',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            97 =>
                array (
                    'id' => 98,
                    'rtl' => 0,
                    'name' => 'Romanian - română',
                    'short' => 'ro',
                    'image_dir' => NULL,
                    'image' => 'ro.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            98 =>
                array (
                    'id' => 99,
                    'rtl' => 0,
                    'name' => 'Romanian (Moldova) - română (Moldova)',
                    'short' => 'mo',
                    'image_dir' => NULL,
                    'image' => 'mo.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            99 =>
                array (
                    'id' => 100,
                    'rtl' => 0,
                    'name' => 'Romansh - rumantsch',
                    'short' => 'rm',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            100 =>
                array (
                    'id' => 101,
                    'rtl' => 0,
                    'name' => 'Russian - русский',
                    'short' => 'ru',
                    'image_dir' => NULL,
                    'image' => 'ru.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            101 =>
                array (
                    'id' => 102,
                    'rtl' => 0,
                    'name' => 'Scottish Gaelic',
                    'short' => 'gd',
                    'image_dir' => NULL,
                    'image' => 'gd.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            102 =>
                array (
                    'id' => 103,
                    'rtl' => 0,
                    'name' => 'Serbian - српски',
                    'short' => 'sr',
                    'image_dir' => NULL,
                    'image' => 'sr.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            103 =>
                array (
                    'id' => 104,
                    'rtl' => 0,
                    'name' => 'Serbo-Croatian - Srpskohrvatski',
                    'short' => 'sh',
                    'image_dir' => NULL,
                    'image' => 'sh.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            104 =>
                array (
                    'id' => 105,
                    'rtl' => 0,
                    'name' => 'Shona - chiShona',
                    'short' => 'sn',
                    'image_dir' => NULL,
                    'image' => 'sn.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            105 =>
                array (
                    'id' => 106,
                    'rtl' => 0,
                    'name' => 'Sindhi',
                    'short' => 'sd',
                    'image_dir' => NULL,
                    'image' => 'sd.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            106 =>
                array (
                    'id' => 107,
                    'rtl' => 0,
                    'name' => 'Sinhala - සිංහල',
                    'short' => 'si',
                    'image_dir' => NULL,
                    'image' => 'si.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            107 =>
                array (
                    'id' => 108,
                    'rtl' => 0,
                    'name' => 'Slovak - slovenčina',
                    'short' => 'sk',
                    'image_dir' => NULL,
                    'image' => 'sk.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            108 =>
                array (
                    'id' => 109,
                    'rtl' => 0,
                    'name' => 'Slovenian - slovenščina',
                    'short' => 'sl',
                    'image_dir' => NULL,
                    'image' => 'sl.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            109 =>
                array (
                    'id' => 110,
                    'rtl' => 0,
                    'name' => 'Somali - Soomaali',
                    'short' => 'so',
                    'image_dir' => NULL,
                    'image' => 'so.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            110 =>
                array (
                    'id' => 111,
                    'rtl' => 0,
                    'name' => 'Southern Sotho',
                    'short' => 'st',
                    'image_dir' => NULL,
                    'image' => 'st.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            111 =>
                array (
                    'id' => 112,
                    'rtl' => 0,
                    'name' => 'Spanish - español',
                    'short' => 'es',
                    'image_dir' => NULL,
                    'image' => 'es.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            112 =>
                array (
                    'id' => 113,
                    'rtl' => 0,
                    'name' => 'Spanish (Argentina) - español (Argentina)',
                    'short' => 'es-AR',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            113 =>
                array (
                    'id' => 114,
                    'rtl' => 0,
                    'name' => 'Spanish (Latin America) - español (Latinoamérica)',
                    'short' => 'es-419',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            114 =>
                array (
                    'id' => 115,
                    'rtl' => 0,
                    'name' => 'Spanish (Mexico) - español (México)',
                    'short' => 'es-MX',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            115 =>
                array (
                    'id' => 116,
                    'rtl' => 0,
                    'name' => 'Spanish (Spain) - español (España)',
                    'short' => 'es-ES',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            116 =>
                array (
                    'id' => 117,
                    'rtl' => 0,
                    'name' => 'Spanish (United States) - español (Estados Unidos)',
                    'short' => 'es-US',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            117 =>
                array (
                    'id' => 118,
                    'rtl' => 0,
                    'name' => 'Sundanese',
                    'short' => 'su',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            118 =>
                array (
                    'id' => 119,
                    'rtl' => 0,
                    'name' => 'Swahili - Kiswahili',
                    'short' => 'sw',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            119 =>
                array (
                    'id' => 120,
                    'rtl' => 0,
                    'name' => 'Swedish - svenska',
                    'short' => 'sv',
                    'image_dir' => NULL,
                    'image' => 'sv.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            120 =>
                array (
                    'id' => 121,
                    'rtl' => 0,
                    'name' => 'Tajik - тоҷикӣ',
                    'short' => 'tg',
                    'image_dir' => NULL,
                    'image' => 'tg.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            121 =>
                array (
                    'id' => 122,
                    'rtl' => 0,
                    'name' => 'Tamil - தமிழ்',
                    'short' => 'ta',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            122 =>
                array (
                    'id' => 123,
                    'rtl' => 0,
                    'name' => 'Tatar',
                    'short' => 'tt',
                    'image_dir' => NULL,
                    'image' => 'tt.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            123 =>
                array (
                    'id' => 124,
                    'rtl' => 0,
                    'name' => 'Telugu - తెలుగు',
                    'short' => 'te',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            124 =>
                array (
                    'id' => 125,
                    'rtl' => 0,
                    'name' => 'Thai - ไทย',
                    'short' => 'th',
                    'image_dir' => NULL,
                    'image' => 'th.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            125 =>
                array (
                    'id' => 126,
                    'rtl' => 0,
                    'name' => 'Tigrinya - ትግርኛ',
                    'short' => 'ti',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            126 =>
                array (
                    'id' => 127,
                    'rtl' => 0,
                    'name' => 'Tongan - lea fakatonga',
                    'short' => 'to',
                    'image_dir' => NULL,
                    'image' => 'to.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            127 =>
                array (
                    'id' => 128,
                    'rtl' => 0,
                    'name' => 'Turkish - Türkçe',
                    'short' => 'tr',
                    'image_dir' => NULL,
                    'image' => 'tr.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            128 =>
                array (
                    'id' => 129,
                    'rtl' => 0,
                    'name' => 'Turkmen',
                    'short' => 'tk',
                    'image_dir' => NULL,
                    'image' => 'tk.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            129 =>
                array (
                    'id' => 130,
                    'rtl' => 0,
                    'name' => 'Twi',
                    'short' => 'tw',
                    'image_dir' => NULL,
                    'image' => 'tw.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            130 =>
                array (
                    'id' => 131,
                    'rtl' => 0,
                    'name' => 'Ukrainian - українська',
                    'short' => 'uk',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            131 =>
                array (
                    'id' => 132,
                    'rtl' => 0,
                    'name' => 'Urdu - اردو',
                    'short' => 'ur',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            132 =>
                array (
                    'id' => 133,
                    'rtl' => 0,
                    'name' => 'Uyghur',
                    'short' => 'ug',
                    'image_dir' => NULL,
                    'image' => 'ug.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            133 =>
                array (
                    'id' => 134,
                    'rtl' => 0,
                    'name' => 'Uzbek - o‘zbek',
                    'short' => 'uz',
                    'image_dir' => NULL,
                    'image' => 'uz.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            134 =>
                array (
                    'id' => 135,
                    'rtl' => 0,
                    'name' => 'Vietnamese - Tiếng Việt',
                    'short' => 'vi',
                    'image_dir' => NULL,
                    'image' => 'vi.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            135 =>
                array (
                    'id' => 136,
                    'rtl' => 0,
                    'name' => 'Walloon - wa',
                    'short' => 'wa',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            136 =>
                array (
                    'id' => 137,
                    'rtl' => 0,
                    'name' => 'Welsh - Cymraeg',
                    'short' => 'cy',
                    'image_dir' => NULL,
                    'image' => 'cy.png',
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            137 =>
                array (
                    'id' => 138,
                    'rtl' => 0,
                    'name' => 'Western Frisian',
                    'short' => 'fy',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            138 =>
                array (
                    'id' => 139,
                    'rtl' => 0,
                    'name' => 'Xhosa',
                    'short' => 'xh',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            139 =>
                array (
                    'id' => 140,
                    'rtl' => 0,
                    'name' => 'Yiddish',
                    'short' => 'yi',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            140 =>
                array (
                    'id' => 141,
                    'rtl' => 0,
                    'name' => 'Yoruba - Èdè Yorùbá',
                    'short' => 'yo',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            141 =>
                array (
                    'id' => 142,
                    'rtl' => 0,
                    'name' => 'Zulu - isiZulu',
                    'short' => 'zu',
                    'image_dir' => NULL,
                    'image' => NULL,
                    'default' => 0,
                    'active' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
        ));
        \DB::table('languages')->whereIn('short',['ar','en'])->update(['active'=>1]);
        \DB::table('languages')->where('short','en')->update(['default'=>1]);
    }
}
