<?php

namespace Database\Seeders;

use App\Models\Currency;
use App\Models\Language;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \DB::table('settings')->delete();

        \DB::table('settings')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'key' => 'multi_language',
                    'value' => 1,
                    'type' => 'select',
                    'table_name' =>NULL,
                    'section' => 'General',
                    'section_sort' => 1,
                    'label' => 'Multi Language',
                    'options' => '["no","yes"]',
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            1 =>
                array (
                    'id' => 2,
                    'key' => 'default_language_id',
                    'value' => 26,
                    'type' => 'select',
                    'table_name' =>Language::class,
                    'section' => 'General',
                    'section_sort' => 2,
                    'label' => 'Default Language',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            2 =>
                array (
                    'id' => 3,
                    'key' => 'multi_currency',
                    'value' => 1,
                    'type' => 'select',
                    'table_name' =>NULL,
                    'section' => 'General',
                    'section_sort' => 3,
                    'label' => 'Multi Currency',
                    'options' => '["no","yes"]',
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            3 =>
                array (
                    'id' => 4,
                    'key' => 'default_currency_id',
                    'value' => 1,
                    'type' => 'select',
                    'table_name' =>Currency::class,
                    'section' => 'General',
                    'section_sort' => 4,
                    'label' => 'Default Currency',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            4 =>
                array (
                    'id' => 5,
                    'key' => 'booking_expired',
                    'value' => 3,
                    'type' => 'input_number',
                    'table_name' =>NULL,
                    'section' => 'General',
                    'section_sort' => 5,
                    'label' => 'Booking expiration days',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            5 =>
                array (
                    'id' => 6,
                    'key' => 'offline',
                    'value' => 0,
                    'type' => 'select',
                    'table_name' =>NULL,
                    'section' => 'General',
                    'section_sort' => 6,
                    'label' => 'Offline',
                    'options' => '["Disabled","Enabled"]',
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            6 =>
                array (
                    'id' => 7,
                    'key' => 'offline_message',
                    'value' => 'We are sorry we will come back as soon as possible',
                    'type' => 'textarea',
                    'table_name' =>NULL,
                    'section' => 'General',
                    'section_sort' => 7,
                    'label' => 'Offline Message',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            7 =>
                array (
                    'id' => 8,
                    'key' => 'google_map_api',
                    'value' => NULL,
                    'type' => 'input_text',
                    'table_name' =>NULL,
                    'section' => 'General',
                    'section_sort' => 8,
                    'label' => 'Google Map Api',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            8 =>
                array (
                    'id' => 9,
                    'key' => 'google_analyses_script',
                    'value' => NULL,
                    'type' => 'textarea',
                    'table_name' =>NULL,
                    'section' => 'General',
                    'section_sort' => 9,
                    'label' => 'Google analyses scripts',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            9 =>
                array (
                    'id' => 10,
                    'key' => 'water_mark',
                    'value' => 0,
                    'type' => 'select',
                    'table_name' =>NULL,
                    'section' => 'Watermark',
                    'section_sort' => 1,
                    'label' => 'Watermark',
                    'options' => '["no","yes"]',
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            10 =>
                array (
                    'id' => 11,
                    'key' => 'water_mark_position',
                    'value' => NULL,
                    'type' => 'select',
                    'table_name' =>NULL,
                    'section' => 'Watermark',
                    'section_sort' => 2,
                    'label' => 'Watermark Position',
                    'options' => '{"tr":"Top Right","tl":"Top Left","tc":"Top Center","bc":"Bottom Center","bl":"Bottom Left"}',
                    'help_text' => "Chose water mark position",
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            11 =>
                array (
                    'id' => 12,
                    'key' => 'water_mark_image',
                    'value' => NULL,
                    'type' => 'file',
                    'table_name' =>NULL,
                    'section' => 'Watermark',
                    'section_sort' => 3,
                    'label' => 'Watermark Image',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            12 =>
                array (
                    'id' => 13,
                    'key' => 'sender_email',
                    'value' => 'info@wealiens.com',
                    'type' => 'input_text',
                    'table_name' =>NULL,
                    'section' => 'Email Setting',
                    'section_sort' => 1,
                    'label' => 'Sender Email',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            13 =>
                array (
                    'id' => 14,
                    'key' => 'sender_email_header',
                    'value' => '',
                    'type' => 'textarea',
                    'table_name' =>NULL,
                    'section' => 'Email Setting',
                    'section_sort' => 2,
                    'label' => 'Sender email header',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            14 =>
                array (
                    'id' => 15,
                    'key' => 'sender_email_footer',
                    'value' => NULL,
                    'type' => 'textarea',
                    'table_name' =>NULL,
                    'section' => 'Email Setting',
                    'section_sort' => 3,
                    'label' => 'Sender email footer',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            15 =>
                array (
                    'id' => 16,
                    'key' => 'contact_phone',
                    'value' => NULL,
                    'type' => 'input_text',
                    'table_name' =>NULL,
                    'section' => 'Contact',
                    'section_sort' => 1,
                    'label' => 'Contact phone',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            16 =>
                array (
                    'id' => 17,
                    'key' => 'contact_email',
                    'value' => NULL,
                    'type' => 'input_text',
                    'table_name' =>NULL,
                    'section' => 'Contact',
                    'section_sort' => 2,
                    'label' => 'Contact email',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            17 =>
                array (
                    'id' => 18,
                    'key' => 'contact_address',
                    'value' => NULL,
                    'type' => 'input_text',
                    'table_name' =>NULL,
                    'section' => 'Contact',
                    'section_sort' => 3,
                    'label' => 'Contact address',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            18 =>
                array (
                    'id' => 20,
                    'key' => 'logo_image',
                    'value' => NULL,
                    'type' => 'file',
                    'table_name' =>NULL,
                    'section' => 'Social',
                    'section_sort' => 1,
                    'label' => 'Logo',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            19 =>
                array (
                    'id' => 21,
                    'key' => 'favorite_icon',
                    'value' => NULL,
                    'type' => 'file',
                    'table_name' =>NULL,
                    'section' => 'Social',
                    'section_sort' => 2,
                    'label' => 'Favorite Icon',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            20 =>
                array (
                    'id' => 22,
                    'key' => 'google_link',
                    'value' => NULL,
                    'type' => 'input_url',
                    'table_name' =>NULL,
                    'section' => 'Social',
                    'section_sort' => 3,
                    'label' => 'Google',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            22 =>
                array (
                    'id' => 24,
                    'key' => 'facebook_link',
                    'value' => NULL,
                    'type' => 'input_url',
                    'table_name' =>NULL,
                    'section' => 'Social',
                    'section_sort' => 5,
                    'label' => 'Facebook',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            23 =>
                array (
                    'id' => 25,
                    'key' => 'vimeo_link',
                    'value' => NULL,
                    'type' => 'input_url',
                    'table_name' =>NULL,
                    'section' => 'Social',
                    'section_sort' => 6,
                    'label' => 'Vimeo',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            24 =>
                array (
                    'id' => 26,
                    'key' => 'twitter_link',
                    'value' => NULL,
                    'type' => 'input_url',
                    'table_name' =>NULL,
                    'section' => 'Social',
                    'section_sort' => 7,
                    'label' => 'Twitter',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            25 =>
                array (
                    'id' => 27,
                    'key' => 'rss_link',
                    'value' => NULL,
                    'type' => 'input_url',
                    'table_name' =>NULL,
                    'section' => 'Social',
                    'section_sort' => 8,
                    'label' => 'Rss',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            26 =>
                array (
                    'id' => 28,
                    'key' => 'dribbble_link',
                    'value' => NULL,
                    'type' => 'input_url',
                    'table_name' =>NULL,
                    'section' => 'Social',
                    'section_sort' => 9,
                    'label' => 'Dribbble',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            27 =>
                array (
                    'id' => 29,
                    'key' => 'pinterest_link',
                    'value' => NULL,
                    'type' => 'input_url',
                    'table_name' =>NULL,
                    'section' => 'Social',
                    'section_sort' => 10,
                    'label' => 'Pinterest',
                    'options' => NULL,
                    'help_text' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),

        ));
        \DB::table('settings')->update(['created_at'=>now()]);
        \DB::table('settings')->where('type','file')->update(['accept'=>'.png, .jpg, .jpeg,.ico']);
    }
}
